name: Publish wheels to testpypi

on: workflow_dispatch

jobs:
  publish_test:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/charm4py

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          nname: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
