name: Publish wheels to testpypi

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        description: "The workflow ID to pull wheels from"
        required: true
        type: string

jobs:
  publish_test:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/charm4py

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-* # download all the wheels
          path: dist
          merge-multiple: true
          run-id: ${{ github.event.inputs.workflow_id }}
      - name: Check status
        run: ls -l dist
      # - name: Publish distribution 📦 to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/
